remote_theme: daattali/beautiful-jekyll
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

title: Las Pegasus Team
author: IlyaBOT, Ponfertato, SuperNyanCat

navbar-links:
  PLAY: steam://connect/95.84.136.207:27015
  Rules: /rules/
  Blog: /blog/
  Steam Group: https://steamcommunity.com/groups/LasPegasusCommunity
  Discord Server: https://discord.com/invite/fgpehrfu

avatar: "/assets/img/laspimg.png"
round-avatar: false

social-network-links:
  #email: "someone@example.com"
  #rss: true
  #facebook: deanattali
  #github: IlyaBOT
  #twitter: daattali
  #patreon: DeanAttali
  #youtube: c/daattali
  #  reddit: yourname
  #  stackoverflow: "3943160/daattali"
  #  spotify: yourname
  #  telephone: +14159998888
  steam: LasPegasusCommunity
  #  twitch: yourname
  #  telegram: yourname
  #  google-scholar: your google scholar
  discord: invite/fgpehrfu

share-links-active:
  twitter: true
  facebook: true
  #linkedin: false
  vk: true

excerpt_length: 50
feed_show_excerpt: false
feed_show_tags: false

keywords: "MLP, GMod, My Little Pony, Bronies, Garry's, Mod, Valve, Source, Construct, Cinema"

navbar-col: "#8461AD"
navbar-text-col: "#FFFFFF"
navbar-border-col: "#DDDDDD"
page-col: "#222222"
text-col: "#FFFFFF"
link-col: "#9F52FF"
hover-col: "#E0C8FF"
footer-col: "#222222"
footer-text-col: "#888888"
footer-link-col: "#9F52FF"
footer-hover-col: "#8461AD"

#mobile-theme-col: "#0085A1"

site-css: "/assets/css/custom-styles.css"
site-js: "/assets/js/custom-script.js"

timezone: "Russia/Moscow"
permalink: /:year-:month-:day-:title/
paginate: 5
paginate_path: "/page:num/"

#disqus: "laspegasus"
#google_analytics: "UA-59820529-1"
#fb_app_id: "536330676521989"

#url-canonical: https://github.com/sponsors/daattali

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      carbonads: true
      comments: true
      social-share: true
      show-share: true
      show-subscribe: true
      support_promo_box: true
      after-content: [share-section.html, scroll-box.html]
  - scope:
      path: "notblog"
    values:
      layout: "post"
      carbonads: true
      comments: true
      social-share: true
      show-share: true
      show-subscribe: true
      support_promo_box: true
      after-content: [share-section.html, scroll-box.html]
  - scope:
      path: "pages"
    values:
      layout: "page"
      comments: true
  - scope:
      path: ""
    values:
      layout: "page"
      before-content: [support_promo_box.html, carbonads.html]
      footer-extra: footer-subscribe.html

exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - docs/
  - files/java/Scrabble/*
# 2fc73a3a967e97599c9763d05e564189d5
